name: docs
channels:
  - conda-forge
dependencies:
  - python
  - pip

  - numpy
  - pandas

  - pytorch-cpu
  - pytorch-ignite

  - mlflow<2.16
  - scikit-learn>=1.0

  - tqdm

  - sphinxcontrib-bibtex
  - sphinx_rtd_theme

  - pip:
    - molgrid
