name: CI

on:
    # GitHub has started calling new repo's first branch "main" https://github.com/github/renaming
    # Existing codes likely still have "master" as the primary branch
    # Both are tracked here to keep legacy and new codes working
    push:
        branches:
            - "master"
            - "main"
    pull_request:
        branches:
            - "master"
            - "main"
    schedule:
        # Nightly tests run on master by default:
        #   Scheduled workflows run on the latest commit on the default or base branch.
        #   (from https://help.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule)
        - cron: "0 0 * * *"

jobs:
    test:
        name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.12", "3.13", "3.14"]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Infos
              shell: bash
              run: |
                  uname -a
                  df -h
                  ulimit -a

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  python-version: ${{ matrix.python-version }}
                  enable-cache: true
                  cache-dependency-glob: "pyproject.toml"

            - name: Install package
              run: uv sync --extra all --extra test

            - name: Run tests
              run: uv run pytest -v --cov=gninatorch --cov-report=xml --color=yes tests/ --nogpu

            - name: CodeCov
              uses: codecov/codecov-action@v5
              with:
                  files: ./coverage.xml
                  flags: unittests
                  name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
